/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function consoleLoggerInit(
  logLevel: LogLevel,
  debugLog: (message?: any, ...optionalParams: any[]) => void,
  infoLog: (message?: any, ...optionalParams: any[]) => void,
  warnLog: (message?: any, ...optionalParams: any[]) => void,
  errorLog: (message?: any, ...optionalParams: any[]) => void,
): string | null;

export interface DynamicConfigNapi {
  name: string;
  jsonValue: string;
  ruleID: string;
  idType: string;
}

export interface ExperimentNapi {
  name: string;
  jsonValue: string;
  ruleID: string;
  idType: string;
}

export interface FeatureGateNapi {
  name: string;
  value: boolean;
  ruleID: string;
  idType: string;
}

export interface LayerNapi {
  name: string;
  ruleID: string;
  idType: string;
  __jsonValue: string;
}

export declare const enum LogLevel {
  None = 0,
  Error = 1,
  Warn = 2,
  Info = 3,
  Debug = 4,
}

export declare function statsigCheckGate(
  statsigRef: number,
  userRef: number,
  gateName: string,
): boolean;

export declare function statsigCreate(
  sdkKey: string,
  optionsRef?: number | undefined | null,
): number;

export declare function statsigGetClientInitResponse(
  statsigRef: number,
  userRef: number,
): string;

export declare function statsigGetCurrentValues(
  statsigRef: number,
): string | null;

export declare function statsigGetDynamicConfig(
  statsigRef: number,
  userRef: number,
  dynamicConfigName: string,
): DynamicConfigNapi;

export declare function statsigGetExperiment(
  statsigRef: number,
  userRef: number,
  experimentName: string,
): ExperimentNapi;

export declare function statsigGetFeatureGate(
  statsigRef: number,
  userRef: number,
  gateName: string,
): FeatureGateNapi;

export declare function statsigGetLayer(
  statsigRef: number,
  userRef: number,
  layerName: string,
): LayerNapi;

export declare function statsigInitialize(statsigRef: number): Promise<void>;

export declare function statsigLogLayerParamExposure(
  statsigRef: number,
  layerData: string,
  paramName: string,
): void;

export declare function statsigLogStringValueEvent(
  statsigRef: number,
  userRef: number,
  eventName: string,
  value?: string | undefined | null,
  metadata?: Record<string, string> | undefined | null,
): void;

export declare function statsigOptionsCreate(
  environment?: string | undefined | null,
  specsUrl?: string | undefined | null,
  logEventUrl?: string | undefined | null,
): number;

export declare function statsigOptionsRelease(userRef: number): void;

export declare function statsigRelease(statsigRef: number): void;

export declare function statsigShutdown(statsigRef: number): Promise<void>;

export declare function statsigUserCreate(
  userId?: string | undefined | null,
  customIds?: Record<string, string> | undefined | null,
  email?: string | undefined | null,
  ip?: string | undefined | null,
  userAgent?: string | undefined | null,
  country?: string | undefined | null,
  locale?: string | undefined | null,
  appVersion?: string | undefined | null,
  custom?: Record<string, string> | undefined | null,
  privateAttributes?: Record<string, string> | undefined | null,
): number;

export declare function statsigUserRelease(userRef: number): void;
