FROM ubuntu:noble-20241011

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-venv \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip3 install statsig-python-core --pre --break-system-packages

COPY examples/python/verify-package .


CMD ["python3", "verify.py"]