FROM debian:11-slim

RUN apt-get update
RUN apt-get install -y \
    php php-curl php-xml composer unzip php-cli php-json php-zip php-ffi

COPY examples/php/verify-package app

WORKDIR /app

RUN echo "ffi.enable=1" > /etc/php/7.4/cli/conf.d/docker-php-ext-ffi.ini

RUN composer require statsig/statsig-php-core:dev-main

CMD ["php", "verify.php"]