FROM golang:1.24-alpine

RUN apk add --no-cache alpine-sdk

WORKDIR /app

COPY examples/go/verify-package .

RUN cat go.sum

RUN go get -u ./...
RUN go mod tidy

CMD ["go", "run", "-tags", "musl", "."]
