FROM azul/zulu-openjdk-alpine:21

RUN apk update && apk add --no-cache gradle
RUN apk add --no-cache libgcc gcompat

WORKDIR /app

COPY examples/java/gradlew ./gradlew
COPY examples/java/gradle ./gradle

COPY examples/java/settings.gradle.kts ./settings.gradle.kts
COPY examples/java/verify-package/build.gradle ./build.gradle
COPY examples/java/verify-package/Verify.java ./src/main/java/Verify.java
RUN chmod +x ./gradlew
RUN ./gradlew --no-daemon clean shadowJar
RUN ./gradlew shadowJar --no-daemon
RUN cp build/libs/*-all.jar /app/app-all.jar
CMD ["java", "-jar", "/app/app-all.jar"]