name: Statsig Node Api Publish

env:
  NPM_TOKEN: ${{ secrets.SIGSTAT_PUBLISH_NPM }}
  GH_APP_ID: '229901'
  GH_APP_INSTALLATION_ID: '36921303'
  GH_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'The StatsigNapi workflow run that built the artifacts to publish'
        required: true
      release_commit_sha:
        description: 'The commit SHA of the Statsig release tag that contains all the artifacts to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-24.04 # need node 20+
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4

      - name: Get Workflow Run Info
        uses: ./.github/actions/verify-workflow-run-successful
        with:
          workflow_run_id: ${{ github.event.inputs.workflow_run_id }}

      - name: Checkout specific commit
        run: |
          git fetch
          git checkout ${{ github.event.inputs.release_commit_sha }}
          git submodule update --init --recursive
          
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Install NPM Dependencies
        run: cd cli && pnpm install

      - name: Run Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          ./run napi-pub ${{ github.event.repository.name }}
