name: 'Get Workflow Run Info'
description: 'Fetches information about a workflow run and validates its status'

inputs:
  workflow_run_id:
    description: 'The ID of the workflow run to check'
    required: true

outputs:
  commit_sha:
    description: 'The commit SHA from the workflow run'
    value: ${{ steps.get_info.outputs.result.commit_sha }}

runs:
  using: 'composite'
  steps:
    - name: Get Workflow Run Info
      uses: actions/github-script@v7
      with:
        script: |
          const run_id = '${{ inputs.workflow_run_id }}';

          const run = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run_id
          });
          
          const commit_sha = run.data.head_sha;

          console.log(`Workflow Run Name: ${run.data.name}`);
          console.log(`Workflow Run Status: ${run.data.status}`);
          console.log(`Workflow Run Conclusion: ${run.data.conclusion}`);
          console.log(`Workflow Run SHA: ${commit_sha}`);

          if (run.data.status !== 'completed' || run.data.conclusion !== 'success') {
            console.error(`StatsigFFI with ID ${run_id} has not completed successfully`);
            process.exit(1);
          }

          return { commit_sha };
