name: Build Statsig Napi
description: Builds Statsig Napi libraries for specified targets

inputs:
  target:
    description: 'Target triple (e.g., aarch64-apple-darwin)'
    required: true

  gh_token:
    description: 'GitHub token'
    required: true

  extras:
    description: 'Extra flags to pass to the build command'
    required: false

  node_arch:
    description: 'Node architecture (e.g., x64)'
    required: false

  include_js_files:
    description: 'Include js files in the release'
    required: false

runs:
  using: composite
  steps:
    - name: Echo Inputs
      shell: bash
      run: |
        echo "Target: ${{ inputs.target }}"

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ inputs.gh_token }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        architecture: ${{ inputs.node_arch || '' }}

    - name: Install CLI Dependencies
      shell: bash
      run: cd cli && pnpm install

    - name: Install Rust Tools
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ inputs.target }}

    - name: "[Windows-i686] Set Supported Architectures"
      if: inputs.target == 'i686-pc-windows-msvc'
      shell: bash
      run: pnpm config set supportedArchitectures.cpu "ia32"

    - name: "[Linux-Musl] Add Zig Compiler"
      if: ${{ contains(inputs.target, 'musl') }}
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: "[MacOS-Arm] Configure C/C++ Compiler"
      if: inputs.target == 'aarch64-apple-darwin'
      shell: bash
      run: ./tools/node/macos_arm_fixes

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
      working-directory: statsig-napi

    - name: Build Napi
      shell: bash
      run: |
        ./tore napi-build \
          --release \
          ${{ !inputs.include_js_files && '--skip-js-optimizations' }} \
          --target ${{ inputs.target }} ${{ inputs.extras }}
