// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Statsig
{
    internal static unsafe partial class StatsigFFI
    {
        const string __DllName = "libstatsig_ffi";



        [DllImport(__DllName, EntryPoint = "statsig_options_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong statsig_options_create(byte* specs_url, byte* log_event_url, ulong specs_adapter_ref, ulong event_logging_adapter_ref, byte* environment, int _event_logging_flush_interval_ms, int event_logging_max_queue_size, int specs_sync_interval_ms, byte* output_log_level, int disable_country_lookup, int disable_user_agent_parsing, int wait_for_country_lookup_init, int wait_for_user_agent_init, int enable_id_lists, byte* id_lists_url, int id_lists_sync_interval_ms, int disable_all_logging, byte* global_custom_fields);

        [DllImport(__DllName, EntryPoint = "statsig_options_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_options_release(ulong options_ref);

        [DllImport(__DllName, EntryPoint = "statsig_user_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong statsig_user_create(byte* user_id, byte* custom_ids_json, byte* email, byte* ip, byte* user_agent, byte* country, byte* locale, byte* app_version, byte* custom_json, byte* private_attributes_json);

        [DllImport(__DllName, EntryPoint = "statsig_user_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_user_release(ulong user_ref);

        [DllImport(__DllName, EntryPoint = "statsig_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong statsig_create(byte* sdk_key, ulong options_ref);

        [DllImport(__DllName, EntryPoint = "statsig_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_release(ulong statsig_ref);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void statsig_initialize_callback_delegate();

        [DllImport(__DllName, EntryPoint = "statsig_initialize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_initialize(ulong statsig_ref, statsig_initialize_callback_delegate callback);

        [DllImport(__DllName, EntryPoint = "statsig_initialize_with_details", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_initialize_with_details(ulong statsig_ref);

        [DllImport(__DllName, EntryPoint = "statsig_initialize_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_initialize_blocking(ulong statsig_ref);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void statsig_shutdown_callback_delegate();

        [DllImport(__DllName, EntryPoint = "statsig_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_shutdown(ulong statsig_ref, statsig_shutdown_callback_delegate callback);

        [DllImport(__DllName, EntryPoint = "statsig_shutdown_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_shutdown_blocking(ulong statsig_ref);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void statsig_flush_events_callback_delegate();

        [DllImport(__DllName, EntryPoint = "statsig_flush_events", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_flush_events(ulong statsig_ref, statsig_flush_events_callback_delegate callback);

        [DllImport(__DllName, EntryPoint = "statsig_flush_events_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_flush_events_blocking(ulong statsig_ref);

        [DllImport(__DllName, EntryPoint = "statsig_get_current_values", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_current_values(ulong statsig_ref);

        [DllImport(__DllName, EntryPoint = "statsig_log_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_log_event(ulong statsig_ref, ulong user_ref, byte* event_json);

        [DllImport(__DllName, EntryPoint = "statsig_identify", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_identify(ulong statsig_ref, ulong user_ref);

        [DllImport(__DllName, EntryPoint = "statsig_get_client_init_response", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_client_init_response(ulong statsig_ref, ulong user_ref, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_parameter_store_with_options", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_parameter_store_with_options(ulong statsig_ref, byte* parameter_store_name, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_string_parameter_from_parameter_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_string_parameter_from_parameter_store(ulong statsig_ref, ulong user_ref, byte* parameter_store_name, byte* param_name, byte* default_value, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_bool_parameter_from_parameter_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool statsig_get_bool_parameter_from_parameter_store(ulong statsig_ref, ulong user_ref, byte* parameter_store_name, byte* param_name, int @default, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_float64_parameter_from_parameter_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern double statsig_get_float64_parameter_from_parameter_store(ulong statsig_ref, ulong user_ref, byte* parameter_store_name, byte* param_name, double @default, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_int_parameter_from_parameter_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern long statsig_get_int_parameter_from_parameter_store(ulong statsig_ref, ulong user_ref, byte* parameter_store_name, byte* param_name, long @default, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_object_parameter_from_parameter_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_object_parameter_from_parameter_store(ulong statsig_ref, ulong user_ref, byte* parameter_store_name, byte* param_name, byte* @default, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_array_parameter_from_parameter_store", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_array_parameter_from_parameter_store(ulong statsig_ref, ulong user_ref, byte* parameter_store_name, byte* param_name, byte* @default, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_check_gate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool statsig_check_gate(ulong statsig_ref, ulong user_ref, byte* gate_name, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_get_feature_gate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_feature_gate(ulong statsig_ref, ulong user_ref, byte* gate_name, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_manually_log_gate_exposure", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_manually_log_gate_exposure(ulong statsig_ref, ulong user_ref, byte* gate_name);

        [DllImport(__DllName, EntryPoint = "statsig_get_dynamic_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_dynamic_config(ulong statsig_ref, ulong user_ref, byte* config_name, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_manually_log_dynamic_config_exposure", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_manually_log_dynamic_config_exposure(ulong statsig_ref, ulong user_ref, byte* config_name);

        [DllImport(__DllName, EntryPoint = "statsig_get_experiment", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_experiment(ulong statsig_ref, ulong user_ref, byte* experiment_name, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_manually_log_experiment_exposure", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_manually_log_experiment_exposure(ulong statsig_ref, ulong user_ref, byte* experiment_name);

        [DllImport(__DllName, EntryPoint = "statsig_get_layer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* statsig_get_layer(ulong statsig_ref, ulong user_ref, byte* layer_name, byte* options_json);

        [DllImport(__DllName, EntryPoint = "statsig_log_layer_param_exposure", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_log_layer_param_exposure(ulong statsig_ref, byte* layer_json, byte* param_name);

        [DllImport(__DllName, EntryPoint = "statsig_manually_log_layer_parameter_exposure", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_manually_log_layer_parameter_exposure(ulong statsig_ref, ulong user_ref, byte* layer_name, byte* param_name);

        [DllImport(__DllName, EntryPoint = "statsig_override_gate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_override_gate(ulong statsig_ref, byte* gate_name, [MarshalAs(UnmanagedType.U1)] bool value, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_override_dynamic_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_override_dynamic_config(ulong statsig_ref, byte* config_name, byte* value_json, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_override_experiment", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_override_experiment(ulong statsig_ref, byte* experiment_name, byte* value_json, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_override_experiment_by_group_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_override_experiment_by_group_name(ulong statsig_ref, byte* experiment_name, byte* group_name, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_override_layer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_override_layer(ulong statsig_ref, byte* layer_name, byte* value_json, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_remove_gate_override", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_remove_gate_override(ulong statsig_ref, byte* gate_name, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_remove_dynamic_config_override", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_remove_dynamic_config_override(ulong statsig_ref, byte* config_name, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_remove_experiment_override", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_remove_experiment_override(ulong statsig_ref, byte* experiment_name, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_remove_layer_override", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_remove_layer_override(ulong statsig_ref, byte* layer_name, byte* id);

        [DllImport(__DllName, EntryPoint = "statsig_remove_all_overrides", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_remove_all_overrides(ulong statsig_ref);

        [DllImport(__DllName, EntryPoint = "statsig_metadata_update_values", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void statsig_metadata_update_values(byte* sdk_type, byte* os, byte* arch, byte* language_version);

        [DllImport(__DllName, EntryPoint = "free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_string(byte* s);


    }



}
