# https://docs.aws.amazon.com/linux/al2/ug/amzn1-amzn2-container.html
FROM --platform=amd64 amazonlinux:2023 AS amazonlinux2023-x86_64

RUN yum update -y \
    && yum install -y \
        gcc \
        openssl-devel \
        protobuf \
        protobuf-compiler \
    && yum clean all

WORKDIR /app

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

ENV TARGET=x86_64-unknown-linux-gnu
RUN rustup target add $TARGET

ENV CARGO_TERM_COLOR=always
ENV EXTRAS=""
ENV CARGO_TARGET_DIR=/app/target/amazonlinux2023-x86_64

CMD ["sh", "-c", "cargo build --target ${TARGET} ${EXTRAS}"]