FROM rust:latest 
 
WORKDIR /app 

ENV CROSS_CONTAINER_IN_CONTAINER=true

RUN curl -fsSL https://get.docker.com | sh

RUN cargo install cross --git https://github.com/cross-rs/cross

RUN rustup target add x86_64-unknown-linux-gnu

RUN cargo new --lib temp-lib
RUN cd temp-lib && cargo build --target x86_64-unknown-linux-gnu
RUN rm -rf temp-lib

ENV CARGO_TERM_COLOR=always
ENV COMMAND="echo 'Error: No Command'"

CMD ["sh", "-c", "$COMMAND"]
