FROM --platform=arm64 amazonlinux:2023 AS amazonlinux2023-arm64

RUN yum update -y \
    && yum install -y \
        gcc \
        openssl-devel \
        protobuf \
        protobuf-compiler \
    && yum clean all

WORKDIR /app

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

ENV TARGET=aarch64-unknown-linux-gnu
RUN rustup target add $TARGET

ENV CARGO_TERM_COLOR=always
ENV EXTRAS=""
ENV CARGO_TARGET_DIR=/app/target/amazonlinux2023

CMD ["sh", "-c", "cargo build --target ${TARGET} ${EXTRAS}"]
