FROM messense/cargo-zigbuild 
 
WORKDIR /app 

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN cargo new --lib temp-lib
RUN cd temp-lib && cargo zigbuild --target aarch64-apple-darwin
RUN rm -rf temp-lib

ENV CARGO_TERM_COLOR=always
ENV COMMAND=""

CMD ["sh", "-c", "$COMMAND"]
