FROM amazonlinux:2023

RUN yum update -y 

RUN yum install gcc -y 
RUN yum install openssl-devel -y 
RUN yum install protobuf protobuf-compiler -y 

WORKDIR /app 

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add x86_64-unknown-linux-gnu

ENV CARGO_TERM_COLOR=always
ENV COMMAND="echo 'Error: No Command'"

CMD ["sh", "-c", "$COMMAND"]
