name: Node E2E Test Release Candidate

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */3 * * *'

env:
  api_key: ${{ secrets.LRS_SERVER_KEY }}
  sdk_repo: private-statsig-server-core

jobs:
  Test:
    if: github.event.repository.private
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        subdir: ['server-core-node-rc']
        platform: ['linux/amd64', 'linux/arm64']
        base_image: ['alpine', 'bookworm-slim', 'bullseye', 'node', 'slim']
    steps:
      - name: Checkout LRS repo
        uses: actions/checkout@v3
        with:
          repository: statsig-io/long-running-sdk
          ref: main
          token: ${{ secrets.ROIM }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: statsig
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: ls -a && cd ./cli && pnpm install
      - name: Build and Test
        id: build_script
        run: cd ./cli && pnpm tsx script.ts -j "build run" -d ${{matrix.subdir}} -p ${{ matrix.platform }} -b ${{matrix.base_image}}
